# Generated by Django 5.0.7 on 2024-08-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('standard_name', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_user', models.BooleanField(default=False)),
            ],
        ),
    ]
